print('Задача 4. Информация о пльзователе')
print('Вариант 1')
your_name = input('Введите имя: ')
your_surname = input('Введите фамилию: ')
print('Вас зовут')
print(your_name)
print(your_surname)
print('Вариант 2')
your_name = input('Введите имя: ')
your_surname = input('Введите фамилию: ')
your_city = input('Введите город проживания: ')
print('Вас зовут ' + your_name, your_surname)
print('Вы живете в городе '+ your_city)